# Generated by Django 6.1 on 2026-09-01 07:33

import apps.orders.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(db_index=True, default=apps.orders.models.generate_order_reference, help_text='Public-facing unique order reference', max_length=64, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coin', models.CharField(choices=[('USDT_TRC20', 'Tether (TRC-20)'), ('SOL', 'Solana (SOL)'), ('BNB', 'BNB Chain (BEP-20)'), ('BTC', 'Bitcoin (BTC)'), ('USDC_BASE', 'USD Coin (Base)')], max_length=32)),
                ('network', models.CharField(choices=[('TRC20', 'Tron (TRC-20)'), ('SOLANA', 'Solana'), ('BEP20', 'BNB Smart Chain (BEP-20)'), ('BITCOIN', 'Bitcoin Network'), ('BASE', 'Base Network')], max_length=32)),
                ('fiat_amount_ngn', models.DecimalField(decimal_places=2, help_text='Exact amount in NGN the user must pay', max_digits=12)),
                ('crypto_amount', models.DecimalField(decimal_places=8, help_text='Exact crypto amount to be delivered to wallet', max_digits=18)),
                ('quote_rate', models.DecimalField(decimal_places=4, help_text='Locked NGN price per 1 full unit of crypto', max_digits=18)),
                ('service_fee_ngn', models.DecimalField(decimal_places=2, default=0, help_text='SwiftSats platform fee in NGN', max_digits=10)),
                ('network_fee_crypto', models.DecimalField(decimal_places=8, default=0, help_text='Blockchain gas/network fee deducted or covered', max_digits=18)),
                ('wallet_address', models.CharField(db_index=True, max_length=128)),
                ('user_email', models.EmailField(blank=True, help_text='Optional receipt email', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUOTE_LOCKED', 'Quote Locked'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYOUT_PROCESSING', 'Payout Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='QUOTE_LOCKED', max_length=32)),
                ('quote_expires_at', models.DateTimeField(db_index=True)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('virtual_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('virtual_bank_name', models.CharField(blank=True, max_length=64, null=True)),
                ('virtual_account_name', models.CharField(blank=True, max_length=128, null=True)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=64, null=True)),
                ('quidax_payout_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('quidax_swap_id', models.CharField(blank=True, max_length=128, null=True)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('payout_error', models.TextField(blank=True, null=True)),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('payout_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('speed_metric_ms', models.IntegerField(blank=True, help_text='Milliseconds from payment-webhook-received to payout-request-sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Order',
                'verbose_name_plural': 'Crypto Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='orders_status_f8c8df_idx'), models.Index(fields=['coin', '-created_at'], name='orders_coin_1a76ff_idx'), models.Index(fields=['paystack_reference'], name='orders_paystac_976f7f_idx'), models.Index(fields=['quidax_payout_id'], name='orders_quidax__cb0eeb_idx')],
            },
        ),
    ]
