# Generated by Django 6.1 on 2026-09-02 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedPaymentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_reference', models.CharField(db_index=True, max_length=128, unique=True)),
                ('channel', models.CharField(default='NOMBA_WEBHOOK', max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField(default=dict)),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unmatched Payment Alert',
                'verbose_name_plural': 'Unmatched Payment Alerts',
                'db_table': 'unmatched_payment_alerts',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='fiat_amount_expected',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Exact expected NGN amount including unique kobo salt', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nomba_transaction_ref',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='salt_kobo_value',
            field=models.IntegerField(blank=True, help_text='Unique 2-digit kobo salt 11-99', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='coin',
            field=models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('USDC', 'USD Coin (USDC)'), ('BNB', 'BNB Chain (BEP-20)'), ('USDT_ERC20', 'ERC20 Tether'), ('USDT_TRC20', 'TRC20 Tether'), ('SOL', 'Solana (SOL)'), ('USDT_BEP20', 'BEP20 Tether'), ('ETH', 'Ethereum (ETH)'), ('BCH', 'Bitcoin Cash (BCH)'), ('TRX', 'Tron (TRX)'), ('DOGE', 'Dogecoin (DOGE)'), ('POL', 'Polygon (POL)'), ('SHIB', 'Shiba Inu (SHIB)'), ('XLM', 'Stellar (XLM)'), ('USDC_BASE', 'USD Coin (Base)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='network',
            field=models.CharField(choices=[('BITCOIN', 'Bitcoin Network'), ('ERC20', 'Ethereum (ERC-20)'), ('TRC20', 'Tron (TRC-20)'), ('SOLANA', 'Solana'), ('BEP20', 'BNB Smart Chain (BEP-20)'), ('BASE', 'Base Network'), ('BCH', 'Bitcoin Cash Network'), ('DOGE', 'Dogecoin Network'), ('POLYGON', 'Polygon Network'), ('STELLAR', 'Stellar Network')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('QUOTE_LOCKED', 'Quote Locked'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('VERIFYING', 'Verifying Payment'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYOUT_PROCESSING', 'Payout Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='QUOTE_LOCKED', max_length=32),
        ),
    ]
