# Generated by Django 5.2.17 on 2026-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_unmatchedpaymentalert_order_fiat_amount_expected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
