# Generated by Django 5.2.17 on 2026-09-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
        ('orders', '0003_alter_order_virtual_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Registered customer account linked to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('QUOTE_LOCKED', 'Quote Locked'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('VERIFYING', 'Verifying Payment'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYOUT_PROCESSING', 'Payout Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUOTE_LOCKED', max_length=32),
        ),
    ]
