# Generated by Django 6.1 on 2026-09-01 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(db_index=True, help_text='Reference of the associated order', max_length=64)),
                ('from_state', models.CharField(help_text='State before transition', max_length=32)),
                ('to_state', models.CharField(help_text='State after transition', max_length=32)),
                ('actor', models.CharField(choices=[('SYSTEM_WEBHOOK', 'Paystack Webhook Handler'), ('CELERY_WORKER', 'Celery Async Worker'), ('ADMIN', 'Admin User'), ('PUBLIC_USER', 'Public User Session'), ('CRON_CLEANUP', 'Automated Expiry Service')], default='SYSTEM_WEBHOOK', max_length=32)),
                ('actor_id', models.CharField(blank=True, help_text='Admin user ID or worker thread ID', max_length=128, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Detailed payload, error message, or latency data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order_reference', '-timestamp'], name='audit_logs_order_r_b425d8_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_logs_actor_00a123_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_source', models.CharField(db_index=True, help_text='e.g. paystack, quidax', max_length=32)),
                ('event_id', models.CharField(db_index=True, help_text='External unique event identifier', max_length=128)),
                ('payload_hash', models.CharField(help_text='SHA256 hash of payload', max_length=64)),
                ('response_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Idempotency Record',
                'verbose_name_plural': 'Idempotency Records',
                'db_table': 'idempotency_records',
                'constraints': [models.UniqueConstraint(fields=('event_source', 'event_id'), name='unique_source_event_id')],
            },
        ),
    ]
