# Generated by Django 6.1 on 2026-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_mode', models.CharField(choices=[('AUTOMATED', '24/7 Fully Automated (Nomba Webhook)'), ('MANUAL', 'Manual Admin Approval')], default='AUTOMATED', help_text='24/7 automated instant payout vs manual 1-tap admin approval', max_length=20)),
                ('settlement_bank_name', models.CharField(default='Nomba MFB', help_text='Bank name shown to users on checkout', max_length=64)),
                ('settlement_account_name', models.CharField(default='SwiftSats Settlement', help_text='Account name shown on checkout', max_length=128)),
                ('settlement_account_number', models.CharField(default='6010450034', help_text='Settlement account number for user deposits', max_length=32)),
                ('telegram_alerts_enabled', models.BooleanField(default=True, help_text='Dispatch instant alerts to Telegram bot')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
    ]
