# Generated by Django 6.1 on 2026-09-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='rotate_accounts',
            field=models.BooleanField(default=True, help_text='Automatically alternate between Moniepoint and Nomba for each incoming order'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='rotation_counter',
            field=models.IntegerField(default=0, help_text='Internal counter tracking account round-robin rotation'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='settlement_account_name_2',
            field=models.CharField(default='Mahmud Bashir Olakanmi', help_text='Secondary account name for rotation', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='settlement_account_number_2',
            field=models.CharField(default='8072410373', help_text='Secondary account number for rotation', max_length=32),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='settlement_bank_name_2',
            field=models.CharField(default='Nomba MFB', help_text='Secondary bank name for rotation', max_length=64),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_name',
            field=models.CharField(default='Mahmud Bashir Olakanmi', help_text='Primary account name', max_length=128),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_number',
            field=models.CharField(default='8072410373', help_text='Primary account number', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_bank_name',
            field=models.CharField(default='Moniepoint MFB', help_text='Primary bank name', max_length=64),
        ),
    ]
