# Generated by Django 5.2.17 on 2026-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_platformsettings_rotate_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_name',
            field=models.CharField(default='SwiftSats Settlement Desk', help_text='Primary settlement desk account name', max_length=128),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_name_2',
            field=models.CharField(default='SwiftSats Checkout Desk', help_text='Secondary settlement desk account name', max_length=128),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_number',
            field=models.CharField(default='0000000000', help_text='Primary virtual account placeholder', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_number_2',
            field=models.CharField(default='0000000000', help_text='Secondary virtual account placeholder', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_bank_name',
            field=models.CharField(default='Paystack-Titan / Wema', help_text='Primary virtual bank partner', max_length=64),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_bank_name_2',
            field=models.CharField(default='Paystack-Titan / Providus', help_text='Secondary virtual bank partner', max_length=64),
        ),
    ]
