# Generated by Django 5.2.17 on 2026-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_alter_platformsettings_settlement_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='use_paystack_virtual_accounts',
            field=models.BooleanField(default=False, help_text='Generate Paystack dynamic accounts vs Direct Merchant Settlement Bank Account'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='payout_mode',
            field=models.CharField(choices=[('AUTOMATED', '24/7 Fully Automated (Nomba Webhook)'), ('MANUAL', 'Manual Admin Approval')], default='MANUAL', help_text='24/7 automated instant payout vs manual 1-tap admin approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_name',
            field=models.CharField(default='MAHMUD OLASUNKANMI BASHIR', help_text='Primary settlement desk account name', max_length=128),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_number',
            field=models.CharField(default='1028627906', help_text='Primary account number', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_number_2',
            field=models.CharField(default='8029314810', help_text='Secondary virtual account number', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_bank_name',
            field=models.CharField(default='Guaranty Trust Bank', help_text='Primary bank partner', max_length=64),
        ),
    ]
