# Generated by Django 5.2.17 on 2026-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_platformsettings_use_paystack_virtual_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='use_paystack_virtual_accounts',
            field=models.BooleanField(default=True, help_text='Generate Paystack dynamic accounts vs Direct Merchant Settlement Bank Account'),
        ),
    ]
