# Generated by Django 5.2.17 on 2026-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_alter_platformsettings_use_paystack_virtual_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_name',
            field=models.CharField(default='Mahmud Bashir Olasunkanmi', help_text='Primary settlement desk account name', max_length=128),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_account_number',
            field=models.CharField(default='8072410373', help_text='Primary account number', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='settlement_bank_name',
            field=models.CharField(default='OPay', help_text='Primary bank partner', max_length=64),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='use_paystack_virtual_accounts',
            field=models.BooleanField(default=False, help_text='Generate Paystack dynamic accounts vs Direct Merchant Settlement Bank Account'),
        ),
    ]
