# Generated by Django on 2026-09-21

from django.db import migrations


def enforce_opay_settlement(apps, schema_editor):
    PlatformSettings = apps.get_model('admin_api', 'PlatformSettings')
    # Update existing settings row(s) or create if none exists
    updated = PlatformSettings.objects.all().update(
        use_paystack_virtual_accounts=False,
        settlement_bank_name='OPay',
        settlement_account_number='8072410373',
        settlement_account_name='Mahmud Bashir Olasunkanmi',
    )
    if updated == 0:
        PlatformSettings.objects.create(
            use_paystack_virtual_accounts=False,
            settlement_bank_name='OPay',
            settlement_account_number='8072410373',
            settlement_account_name='Mahmud Bashir Olasunkanmi',
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_alter_platformsettings_settlement_account_name_and_more'),
    ]

    operations = [
        migrations.RunPython(enforce_opay_settlement, noop_reverse),
    ]
